name: Update Website STAGE

on:
  # Schedule makes this bot run in regular intervals, without any interventions
  #schedule:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout Git
        uses: actions/checkout@v2

      - name: Setup python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - name: Get pip cache dir
        id: pip-cache
        run: |
          echo "::set-output name=dir::$(pip cache dir)"

      - name: Cache python packages
        uses: actions/cache@v2
        with:
          path: ${{ steps.pip-cache.outputs.dir }}
          key: ${{ runner.os }}-pip-${{ hashFiles('./src/requirements.txt') }}

      - name: Install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r ./src/requirements.txt

      - name: Run python scripts
        env: 
          SHEET_UNITS_POSITION: ${{ secrets.SHEET_UNITS_POSITION }}
          SHEET_UNITS_DESCRIPTION: ${{ secrets.SHEET_UNITS_DESCRIPTION }}
          SHEET_ASSESSMENTS: ${{ secrets.SHEET_ASSESSMENTS }}
          SHEET_BTG: ${{ secrets.SHEET_BTG }}
        run: |
          python ./src/export_data.py -p staging

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "10"
          
      - name: FTP Deploy to WP Engine (Production)
        uses: SamKirkland/FTP-Deploy-Action@3.1.1
        with:
          ftp-server: ${{ secrets.FTP_HOST }}
          ftp-username: ${{ secrets.FTP_USERNAME_STAGE }}
          ftp-password: ${{ secrets.FTP_PASSWORD_STAGE }}
          local-dir: website_tmp
          git-ftp-args: --insecure
